name: flutter_cache_manager
description: Generic cache manager for flutter. Saves web files on the storages of the device and saves the cache info using sqflite.
version: 3.4.0
homepage: https://github.com/Baseflow/flutter_cache_manager/tree/master/flutter_cache_manager

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  clock: ^1.1.1
  collection: ^1.17.0
  file: '>=6.0.0 <8.0.0'
  flutter:
    sdk: flutter
  http: ^1.0.0
  path: ^1.8.0
  path_provider: ^2.0.15
  rxdart: ^0.27.0
  sqflite: ^2.2.0
  uuid: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.1
  flutter_lints: ^2.0.1
